### ISSUE TITLE
Questions about running the ANTM model example

### ISSUE THREAD

**Issue by zdf737477** [hamedR96/ANTM#5]
Sorry to bother you, I encountered the following problem when running the ANTM model example. How can I solve it? Thank you very much.

Aligned Dimension Reduction is initialized...
Traceback (most recent call last):
  File "D:\TopicModel\ANTM-main\ExampleDemo\123.py", line 17, in <module>
    topics_per_period=model.fit(save=True)
                      ^^^^^^^^^^^^^^^^^^^^
  File "D:\TopicModel\ANTM-main\antm\main.py", line 85, in fit
    self.umap_embeddings_clustering, self.umap_embeddings_visulization = aligned_umap(
                                                                         ^^^^^^^^^^^^^
  File "D:\TopicModel\ANTM-main\antm\aligned_clustering_layer.py", line 11, in aligned_umap
    model_umap_clustering = umap.aligned_umap.AlignedUMAP(
                            ^^^^^^^^^^^^^^^^^
AttributeError: module 'umap' has no attribute 'aligned_umap'

Process finished with exit code 1

**Comment by Allaa-boutaleb** [comment]
Hey there!
Have you installed umap using umap-learn? 

Try these following commands:

```
pip uninstall umap
pip install umap-learn
```

Let me know if it works. :)

**Comment by zdf737477** [comment]
> Hey there! Have you installed umap using umap-learn?
> 
> Try these following commands:
> 
> ```
> pip uninstall umap
> pip install umap-learn
> ```
> 
> Let me know if it works. :)



I ran these commands“ > pip uninstall umap
> pip install umap-learn”，but still got the following error：
Aligned Dimension Reduction is initialized...
Traceback (most recent call last):
  File "D:\TopicModel\ANTM-main\ExampleDemo\123.py", line 17, in <module>
    topics_per_period=model.fit(save=True)
                      ^^^^^^^^^^^^^^^^^^^^
  File "D:\TopicModel\ANTM-main\antm\main.py", line 85, in fit
    self.umap_embeddings_clustering, self.umap_embeddings_visulization = aligned_umap(
                                                                         ^^^^^^^^^^^^^
  File "D:\TopicModel\ANTM-main\antm\aligned_clustering_layer.py", line 11, in aligned_umap
    model_umap_clustering = umap.aligned_umap.AlignedUMAP(
                            ^^^^^^^^^^^^^^^^^
AttributeError: module 'umap' has no attribute 'aligned_umap'

Process finished with exit code 1

**Comment by zdf737477** [comment]
I ran these commands“ > pip uninstall umap

pip install umap-learn”，but still got the following error：
Aligned Dimension Reduction is initialized...
Traceback (most recent call last):
File "D:\TopicModel\ANTM-main\ExampleDemo\123.py", line 17, in
topics_per_period=model.fit(save=True)
^^^^^^^^^^^^^^^^^^^^
File "D:\TopicModel\ANTM-main\antm\main.py", line 85, in fit
self.umap_embeddings_clustering, self.umap_embeddings_visulization = aligned_umap(
^^^^^^^^^^^^^
File "D:\TopicModel\ANTM-main\antm\aligned_clustering_layer.py", line 11, in aligned_umap
model_umap_clustering = umap.aligned_umap.AlignedUMAP(
^^^^^^^^^^^^^^^^^
AttributeError: module 'umap' has no attribute 'aligned_umap'

Process finished with exit code 1
